CREATE TABLE `frete_tabela` (
	`id` int AUTO_INCREMENT NOT NULL,
	`uf_origem` varchar(2) NOT NULL,
	`classificacao_origem` varchar(50) NOT NULL,
	`uf_destino` varchar(2) NOT NULL,
	`classificacao_destino` varchar(50) NOT NULL,
	`peso_0_10` int NOT NULL,
	`peso_11_20` int NOT NULL,
	`peso_21_30` int NOT NULL,
	`peso_31_50` int NOT NULL,
	`peso_51_70` int NOT NULL,
	`peso_71_100` int NOT NULL,
	`peso_101_200` int NOT NULL,
	`peso_acima_200` int NOT NULL,
	`ad_valorem_perc` int NOT NULL,
	`ad_valorem_min` int NOT NULL,
	`despacho` int NOT NULL,
	`prod_quimico_perc` int NOT NULL,
	`prod_quimico_ate_100` int NOT NULL,
	`prod_quimico_acima_100` int NOT NULL,
	`tde1_perc` int NOT NULL,
	`tde1_min` int NOT NULL,
	`tde1_max` int NOT NULL,
	`tde2_perc` int NOT NULL,
	`tde2_min` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `frete_tabela_id` PRIMARY KEY(`id`)
);
